### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: CoffeeRocket - кофе на лавочку от 7 мин
email: contact@coffeerocket.ru
description: Доставка кофе и еды по паркам Москвы.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coffeerocket.ru" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
author: Sandoche Adittane
logo: assets/images/large-logo.png

languages: ["ru"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: G-CDJVBL5D6E
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
