name: CoffeeRocket
description: Кофе на лавочку от 7 мин.
full_description: '<div dir="ltr">CoffeeRocket &ndash; якорь вкусной жизни в условиях карантина.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Вау! Пить кофе в любом месте парков Москвы стало реально. Теперь вы можете получить ваши любимые блюда и напитки CoffeeRocket с доставкой.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Порой бывают моменты, когда закапываемся с головой в работу и забываем расслабляться и позволить себе отдых. Пусть доставка свежего кофе и сладостей станет небольшим ресурсом необходимым восполнением вашей энергии.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Загрузите приложение CoffeeRocket, чтобы заказать speciality кофе приготовленного вручную нашими бариста, и выбрать из целого ряда вкусных блюд, сладких или соленых закусок.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Если вам нужно поднять настроение, но вы слишком увлечены, чтобы пойти в один из кофе-шопов - воспользуйтесь нашим сервисом.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Возможности CoffeeRocket:</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">- Заказ привозит курьер на самокате в течении 7-10м.</div>
<div dir="ltr">- Простота оформления заказа. С функцией определения местоположения - геоданные определяются автоматически.</div>
<div dir="ltr">- Доставка в любое время с 10:00 до 21:00: кофе и торт на завтрак, пирог на перекус, запеканка на обед, кекс на ужин.</div>
<div dir="ltr">- Возможность повторного заказа.</div>
<div dir="ltr">- Большой ассортимент предложений для заказа.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">О CoffeeRocket:</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">CoffeeRocket &mdash; это бесплатное приложение, с помощью которого можно приобрести кофе или кондитерские изделия с доставкой по паркам Москвы. При оформлении заказа, курьер доставит вам блюда и многое другое.</div>
<div dir="ltr">&nbsp;</div>
<div dir="ltr">Чтобы сформировать свое мнение о доставке кофе &ndash; сделайте заказ и ощутите будущее на себе.</div>
<div dir="ltr">&nbsp;</div>'
android: https://www.dropbox.com/s/4wmw0exhn72vmjg/Coffeerocket-release.apk?dl=1
iOS: https://apps.apple.com/ua/app/id1528565716
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
